                                                                        Akshay Bhardwaj
                                                                        akshay_bhardwaj2010@yahoo.in

Task 1

1

In [3]:
def div(x,y):
    try:
        result = x/y
        print("The answer is :",result)
    except ZeroDivisionError:
            print("Sorry, you are dividing by Zero")

div(5,0)

Sorry, you are dividing by Zero


2

In [5]:
subject=["Americans", "Indians"]
verb=["Play", "watch"]
obj=["Baseball","cricket"]

sentence_list = [(sub+" "+ vb + " " + ob) for sub in subject for vb in verb for ob in obj]
for sentence in sentence_list:
 print (sentence)

Americans Play Baseball
Americans Play cricket
Americans watch Baseball
Americans watch cricket
Indians Play Baseball
Indians Play cricket
Indians watch Baseball
Indians watch cricket


Task 2

1

In [3]:
import numpy as np

def gen_vander_matrix(ipvector, n, increasing=False):
    
    if not increasing:
        op_matx = np.array([x**(n-1-i) for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    return op_matx

inputvector = np.array([1,2,3,4,5])
no_col_opmat = 3
op_matx_dec_order = gen_vander_matrix(inputvector,no_col_opmat,False)

print("The input array is:",inputvector,"\n")
print("Number of columns in output matrix should be:",no_col_opmat,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",op_matx_dec_order,"\n")

The input array is: [1 2 3 4 5] 

Number of columns in output matrix should be: 3 

Vander matrix of the input array in decreasing order of powers:

 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]] 

